In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import os
os.getcwd()

'/content'

In [3]:
!ls

drive  sample_data


In [0]:
os.chdir('/content/drive/My Drive/App')

In [0]:
import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")

In [80]:
dataset.shape

(10000, 14)

In [81]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
features = dataset.iloc[:,3:13].values
labels = dataset.iloc[:,13].values

In [84]:
features

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [85]:
labels

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer([('encoder',OneHotEncoder(),[1,2])],remainder = 'passthrough')
features = np.array(ct.fit_transform(features) , dtype = np.float32)

In [87]:
features

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085578e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888523e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190781e+04]], dtype=float32)

In [0]:
features = features[:,1:]

In [89]:
features.shape

(10000, 12)

In [0]:
from sklearn.model_selection import train_test_split
features_train,features_test,labels_train,labels_test = train_test_split(features,labels,test_size=0.20,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
featurs_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [92]:
features_train[0]

array([0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       6.6700000e+02, 3.4000000e+01, 5.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.6383064e+05],
      dtype=float32)

In [0]:
# Importing the Keras Library & Packages
import keras
from keras.models import  Sequential
from keras.layers import Dense

In [0]:
classifier = Sequential()

In [95]:
features.shape

(10000, 12)

In [0]:
# Adding the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=12))

In [0]:
# Adding the Second hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [0]:
# Adding the Output Layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [0]:
# Now Compiling the ANN Algorithm
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [100]:
# Now we will be fitting the Model for the New Predictions
classifier.fit(features_train,labels_train,batch_size = 10 , epochs = 10)

Epoch 1/10
8000/8000 [==============================] - 1s 119us/step - loss: 0.6466 - accuracy: 0.7875
Epoch 2/10
8000/8000 [==============================] - 1s 101us/step - loss: 0.5347 - accuracy: 0.7960
Epoch 3/10
8000/8000 [==============================] - 1s 95us/step - loss: 0.5119 - accuracy: 0.7960
Epoch 4/10
8000/8000 [==============================] - 1s 97us/step - loss: 0.5070 - accuracy: 0.7960
Epoch 5/10
8000/8000 [==============================] - 1s 93us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 6/10
8000/8000 [==============================] - 1s 92us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 7/10
8000/8000 [==============================] - 1s 93us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 8/10
8000/8000 [==============================] - 1s 104us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 9/10
8000/8000 [==============================] - 1s 99us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 10/10
8000/8000 [==============================] - 1s 93us/step 

In [0]:
# Now we can predict the new Predictions.
labels_pred = classifier.predict_classes(features_test)

In [102]:
labels_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [103]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test,labels_pred)
cm 

array([[1595,    0],
       [ 405,    0]])