https://blog.paperspace.com/intro-to-optimization-momentum-rmsprop-adam/

In [0]:
import keras

Using TensorFlow backend.


In [0]:
#model.summary()

In [0]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 2s 0us/step


In [0]:
train_images.shape

(60000, 28, 28)

In [0]:
train_images[0].shape



(28, 28)

In [0]:
train_images[10]

In [0]:
train_labels[10]

3

In [0]:
train_images = train_images.reshape((60000, 28, 28, 1))

In [0]:
train_images.shape

(60000, 28, 28, 1)

In [0]:
train_images[0]

In [0]:
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

In [0]:
train_images[0]


In [0]:
train_labels[0]

In [0]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [0]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [0]:
print train_labels.shape

(60000, 10)


In [0]:
from keras import layers
from keras import models

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(16, (5,5), activation = "relu"))
model.add(layers.MaxPooling2D((2, 2)))



In [0]:
model.add(layers.Flatten())

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [0]:

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=50, batch_size=64)

Epoch 1/50
60000/60000 [==============================] - 12s 207us/step - loss: 0.2125 - accuracy: 0.9361
Epoch 2/50
60000/60000 [==============================] - 7s 110us/step - loss: 0.0645 - accuracy: 0.9798
Epoch 3/50
60000/60000 [==============================] - 7s 113us/step - loss: 0.0444 - accuracy: 0.9867
Epoch 4/50
60000/60000 [==============================] - 7s 118us/step - loss: 0.0348 - accuracy: 0.9896
Epoch 5/50
60000/60000 [==============================] - 7s 117us/step - loss: 0.0287 - accuracy: 0.9911
Epoch 6/50
60000/60000 [==============================] - 7s 110us/step - loss: 0.0238 - accuracy: 0.9930
Epoch 7/50
60000/60000 [==============================] - 7s 111us/step - loss: 0.0209 - accuracy: 0.9933
Epoch 8/50
60000/60000 [==============================] - 7s 111us/step - loss: 0.0174 - accuracy: 0.9946
Epoch 9/50
60000/60000 [==============================] - 7s 109us/step - loss: 0.0163 - accuracy: 0.9950
Epoch 10/50
60000/60000 [====================

In [0]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 101us/step


In [0]:
test_images[0].shape

(28, 28, 1)

In [0]:
test_acc


0.9908

In [0]:
model.layers

In [0]:
train_images[0].shape

(28, 28, 1)

In [0]:
type(train_images)

In [0]:
test_data = train_images[10].reshape(1,28,28,1)

In [0]:
test_data.shape

(1, 28, 28, 1)

In [0]:
model.predict_classes(test_data)

array([3])

Set axis=-1 means, extract largest indices in each row. Here we have only one row.

In [0]:
train_labels[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [0]:
train_labels[10].argmax()

3

Code challenge 
https://medium.com/coinmonks/handwritten-digit-prediction-using-convolutional-neural-networks-in-tensorflow-with-keras-and-live-5ebddf46dc8

In [0]:
test_images.shape

(10000, 28, 28, 1)

In [0]:
test_data = test_images

In [0]:
predictions = model.predict_classes(test_data)

In [0]:
from sklearn import metrics

In [0]:

matrix = metrics.confusion_matrix(test_labels.argmax(axis=1), predictions)

In [0]:
print matrix

[[ 973    0    0    0    0    1    1    3    2    0]
 [   0 1130    0    1    0    1    1    2    0    0]
 [   1    1 1022    2    1    0    0    3    2    0]
 [   0    0    0 1004    0    1    0    3    2    0]
 [   0    0    1    0  971    0    1    1    0    8]
 [   2    0    0    9    0  876    1    1    2    1]
 [   5    2    0    1    2    1  945    0    2    0]
 [   0    1    3    0    0    0    0 1022    0    2]
 [   1    0    2    0    0    1    0    0  968    2]
 [   2    0    0    0    4    1    0    3    2  997]]
