In [0]:
import keras

In [0]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images , train_labels) , (test_images , test_labels) = mnist.load_data()

In [64]:
train_images.shape

(60000, 28, 28)

In [65]:
train_images[0].shape

(28, 28)

In [0]:
train_images[0] # It show the pixels of the images from dataset.

In [66]:
train_labels[10]

3

In [67]:
train_images = train_images.reshape((60000,28,28,1))
train_images.shape

(60000, 28, 28, 1)

In [0]:
train_images[0]

In [0]:
train_images = train_images.astype('float32')/255

test_images = test_images.reshape((10000,28,28,1))
test_images = test_images.astype('float32')/255

In [0]:
train_images[0]

In [69]:
train_labels[0]

5

In [70]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [72]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [73]:
print(train_labels.shape)

(60000, 10)


In [0]:
from keras import layers
from keras import models

model = models.Sequential()
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(16, (5,5), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))



In [0]:
model.add(layers.Flatten())

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [77]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(train_images,train_labels,batch_size=64,epochs=50)

Epoch 1/50
60000/60000 [==============================] - 3s 53us/step - loss: 0.0016 - accuracy: 0.9996
Epoch 2/50
60000/60000 [==============================] - 3s 51us/step - loss: 8.5508e-04 - accuracy: 0.9998
Epoch 3/50
60000/60000 [==============================] - 3s 51us/step - loss: 7.6261e-04 - accuracy: 0.9997
Epoch 4/50
60000/60000 [==============================] - 3s 51us/step - loss: 0.0012 - accuracy: 0.9996
Epoch 5/50
60000/60000 [==============================] - 3s 52us/step - loss: 8.1720e-04 - accuracy: 0.9997
Epoch 6/50
60000/60000 [==============================] - 3s 52us/step - loss: 9.5207e-04 - accuracy: 0.9997
Epoch 7/50
60000/60000 [==============================] - 3s 52us/step - loss: 9.5073e-04 - accuracy: 0.9998
Epoch 8/50
60000/60000 [==============================] - 3s 51us/step - loss: 0.0013 - accuracy: 0.9997
Epoch 9/50
60000/60000 [==============================] - 3s 51us/step - loss: 5.7357e-04 - accuracy: 0.9998
Epoch 10/50
60000/60000 [======

In [78]:
test_loss,test_acc = model.evaluate(test_images,test_labels)

10000/10000 [==============================] - 1s 58us/step


In [79]:
test_images[0].shape

(28, 28, 1)

In [80]:
test_acc

0.9909999966621399

In [81]:
test_loss

0.1881453769824824

In [82]:
model.layers

In [83]:
train_images[0].shape

(28, 28, 1)

In [84]:
print(type(train_images))

<class 'numpy.ndarray'>


In [0]:
test_data = train_images[10].reshape(1,28,28,1)

In [86]:
test_data.shape

(1, 28, 28, 1)

In [87]:
model.predict_classes(test_data)

array([3])

Set axis = -1 means, extract largest indices in each row. Here we have only one row.

In [88]:
train_labels[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [89]:
train_labels[10].argmax()

3

In [90]:
test_images.shape

(10000, 28, 28, 1)

In [0]:
test_data = test_images

In [0]:
predictions = model.predict_classes(test_data)

In [93]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_labels.argmax(axis=1),predictions)
cm

array([[ 977,    1,    0,    0,    0,    0,    0,    0,    2,    0],
       [   0, 1128,    0,    0,    2,    1,    0,    3,    1,    0],
       [   0,    1, 1018,    4,    1,    0,    1,    4,    3,    0],
       [   0,    0,    0, 1005,    0,    4,    0,    0,    1,    0],
       [   0,    0,    0,    0,  976,    0,    2,    0,    0,    4],
       [   0,    0,    0,    5,    0,  882,    2,    1,    0,    2],
       [   2,    2,    0,    1,    1,    3,  947,    0,    2,    0],
       [   0,    0,    1,    2,    2,    0,    0, 1021,    1,    1],
       [   1,    0,    0,    0,    1,    1,    0,    2,  968,    1],
       [   3,    0,    0,    4,    8,    3,    0,    1,    2,  988]])