In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import os
os.getcwd()

'/content'

In [3]:
!ls

drive  sample_data


In [0]:
os.chdir('/content/drive/My Drive/App')

In [0]:
import pandas as pd
dataset = pd.read_csv("Social_Network_Ads_2.csv")

In [25]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [26]:
dataset.shape

(400, 5)

In [27]:
dataset.isnull().any(axis=0)

User ID            False
Gender             False
Age                False
EstimatedSalary    False
Purchased          False
dtype: bool

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
features = dataset.iloc[:,[2,3]].values
labels = dataset.iloc[:,-1].values

In [0]:
features

In [34]:
labels.shape

(400,)

In [32]:
features.shape

(400, 2)

In [33]:
features[0]

array([   19, 19000])

In [0]:
from sklearn.model_selection import train_test_split
features_train,features_test,labels_train,labels_test = train_test_split(features,labels,test_size=0.20,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
featurs_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [40]:
features_train[0]

array([    58, 144000])

In [0]:
# Importing the Keras Library & Packages
import keras
from keras.models import  Sequential
from keras.layers import Dense

In [0]:
classifier = Sequential()

In [43]:
features.shape

(400, 2)

In [0]:
# Adding the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=2))

In [0]:
# Adding the Second hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [0]:
# Adding the Output Layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [0]:
# Now Compiling the ANN Algorithm
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [48]:
# Now we will be fitting the Model for the New Predictions
classifier.fit(features_train,labels_train,batch_size = 10 , epochs = 10)

Epoch 1/10
320/320 [==============================] - 0s 1ms/step - loss: 1.0747 - accuracy: 0.4938
Epoch 2/10
320/320 [==============================] - 0s 118us/step - loss: 0.7084 - accuracy: 0.5156
Epoch 3/10
320/320 [==============================] - 0s 118us/step - loss: 0.7010 - accuracy: 0.5063
Epoch 4/10
320/320 [==============================] - 0s 114us/step - loss: 0.6939 - accuracy: 0.5938
Epoch 5/10
320/320 [==============================] - 0s 137us/step - loss: 0.7183 - accuracy: 0.5188
Epoch 6/10
320/320 [==============================] - 0s 126us/step - loss: 0.6945 - accuracy: 0.5500
Epoch 7/10
320/320 [==============================] - 0s 118us/step - loss: 0.6849 - accuracy: 0.6250
Epoch 8/10
320/320 [==============================] - 0s 123us/step - loss: 0.6965 - accuracy: 0.5312
Epoch 9/10
320/320 [==============================] - 0s 120us/step - loss: 0.6935 - accuracy: 0.5562
Epoch 10/10
320/320 [==============================] - 0s 121us/step - loss: 0.6895 

In [0]:
# Now we can predict the new Predictions.
labels_pred = classifier.predict_classes(features_test)

In [0]:
labels_pred

In [51]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test,labels_pred)
cm 

array([[58,  0],
       [22,  0]])